# Generated by Django 4.1.5 on 2023-01-30 11:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_uz', models.TextField()),
                ('text_ru', models.TextField()),
                ('p_number', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='HumanResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_uz', ckeditor.fields.RichTextField()),
                ('text_ru', ckeditor.fields.RichTextField()),
                ('url', models.URLField()),
            ],
        ),
    ]
