# Generated by Django 4.1.5 on 2023-02-04 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('app', '0002_homeview'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HomeView',
            new_name='Main',
        ),
    ]
