# Generated by Django 4.1.5 on 2023-01-30 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_uz', models.CharField(max_length=100)),
                ('title_ru', models.CharField(max_length=100)),
                ('icon', models.FileField(upload_to='about/')),
                ('file', models.FileField(blank=True, null=True, upload_to='about/')),
                ('text_uz', models.TextField(blank=True, null=True)),
                ('text_ru', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='about_file')),
                ('about_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.aboutitem')),
            ],
        ),
    ]
